"""Generate dashboard/gems_logo_data.py from dashboard/assets/*.png.

Embeds PNG bytes as base64 strings in a Python module so deployments do not
depend on Azure/Oryx filesystem layout. Run after updating the PNGs:

    python tools/embed_logos.py

For ``gems_logo.png`` the white background is converted to transparent so the
CSS ``filter: brightness(0) invert(1)`` trick can render it as a clean white
silhouette on the green hero.
"""
from __future__ import annotations

import base64
import io
import pathlib
import textwrap


def _encode_bytes(data: bytes) -> str:
    return base64.b64encode(data).decode("ascii")


def _make_white_transparent(src: pathlib.Path) -> bytes:
    """Return PNG bytes with near-white pixels made transparent.

    Alpha is derived from ``255 - min(R,G,B)`` so anti-aliased edges stay smooth.
    """
    from PIL import Image

    img = Image.open(src).convert("RGBA")
    out = img.copy()
    px_src = img.load()
    px_out = out.load()
    w, h = img.size
    for y in range(h):
        for x in range(w):
            r, g, b, _ = px_src[x, y]
            alpha = min(255, (255 - min(r, g, b)) * 2)
            px_out[x, y] = (r, g, b, alpha)
    buf = io.BytesIO()
    out.save(buf, format="PNG")
    return buf.getvalue()


def main() -> None:
    repo = pathlib.Path(__file__).resolve().parent.parent
    assets = repo / "dashboard" / "assets"
    out = repo / "dashboard" / "gems_logo_data.py"

    gems = _encode_bytes(_make_white_transparent(assets / "gems_logo.png"))
    gmh = _encode_bytes((assets / "global_methane_hub.png").read_bytes())

    def wrap(s: str) -> str:
        return "\n".join(textwrap.wrap(s, 76))

    body = (
        '"""Embedded logo bytes (base64).\n\n'
        "Generated by ``tools/embed_logos.py`` so deployments do not depend on the\n"
        "Azure/Oryx filesystem layout for partner logos.\n"
        '"""\n'
        "from __future__ import annotations\n\n"
        "import base64\n\n"
        f'GEMS_LOGO_PNG_B64 = """\n{wrap(gems)}\n"""\n\n'
        f'GLOBAL_METHANE_HUB_PNG_B64 = """\n{wrap(gmh)}\n"""\n\n\n'
        "def gems_logo_png() -> bytes:\n"
        '    return base64.b64decode("".join(GEMS_LOGO_PNG_B64.split()))\n\n\n'
        "def global_methane_hub_png() -> bytes:\n"
        '    return base64.b64decode("".join(GLOBAL_METHANE_HUB_PNG_B64.split()))\n'
    )
    out.write_text(body, encoding="utf-8")
    print(f"wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
